### ISSUE TITLE
[Assignment 1] gg does not grade my solution

### ISSUE THREAD

**Issue by kingdoctor123** [kaist-cp/cs492-uarch#11]
Hello

I submitted my solution of assignment 1 to gg, but it only says:
```
===== SETUP =====

===== CHECK =====
[2024-09-08 22:16:31,882: WARNING/ForkPoolWorker-128] Demoting to runner...
Successfully submitted!
```

I got the same result even if I submit an empty file (which is clearly a wrong solution).

I wonder if it is an intended result, since I remember that we can see our score from gg at the professor's other classes (e.g. CS220, CS431, ...).

Thank you in advance.

**Comment by minseongg** [comment]
Thanks for the reporting!

We added the grading script for assignment 1, so you can now check the result with the "VALID?" column in the GG.
(If it is "Yes", then you passed the testbench.)

Could you please submit it again?

FYI: For some of the later assignments, grading may take a while, so we plan to accept submissions via GG, but grading will be done offline in batches. Sorry for the inconvenience.

**Comment by kingdoctor123** [comment]
It works now. Thank you so much for your work in weekend
