### ISSUE TITLE
Reset Password Doesn't Work

### ISSUE THREAD

**Issue by izaazm** [kaist-cp/cs492-uarch#12]
I registered for the class a bit late, and up until now, I haven't been able to log in/reset password using the link in the github (https://auth.fearless.systems/if/flow/default-recovery-flow/). There is no verification email in my inbox even after clicking send email again.

**Comment by jeehoonkang** [comment]
Would you all please try again?

**Comment by izaazm** [comment]
It works now, Thank you!
