### ISSUE TITLE
About lecture note of today's lecture

### ISSUE THREAD

**Issue by ki6090** [kaist-cp/cs492-uarch#13]
I would like to review some parts to gain a better understanding about today's lecture. Could you kindly share the lecture notes  that could help clarify the key points discussed?

Thank you for your time and guidance.

**Comment by minseongg** [comment]
You can check out the materials used in the class here:

https://github.com/kaist-cp/cs492-uarch?tab=readme-ov-file#textbook

Could you please check it?

**Comment by ki6090** [comment]
Oh I found the lecture note. Thank you very much.
