### ISSUE TITLE
[Assignment 1] gg seems not working as expected

### ISSUE THREAD

**Issue by killerwhalee** [kaist-cp/cs492-uarch#14]
I submitted my `fir.v` file on gg, and expected to successfully uploaded - as I passed all tests.
However, it fails with warning for install python3.12-venv. And I think it is the problem of gg server.

```
===== CHECK =====
[2024-09-17 04:00:38,115: WARNING/ForkPoolWorker-128] Demoting to runner...
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.12-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: /app/files/checks/887767d0-a2f3-4e27-8e86-e9735a0c1453/venv/bin/python3
```

I wonder is it really a problem of gg or problem of my test server as I used `venv` for setting up my local testing machine.
Thank you in advance.

**Comment by minseongg** [comment]
We found that some packages were removed after rebooting the gg server; now we have fixed the problem.

Could you please submit it again?

Sorry for the inconvenience.

**Comment by killerwhalee** [comment]
Now it works! Thank you for resolving problem in the holiday🥺
Thank you and happy chuseok!
