### ISSUE TITLE
No such file or directory: 'rustup'

### ISSUE THREAD

**Issue by ki6090** [kaist-cp/cs492-uarch#17]
I am working on project2. And I already installed 'rust' in development server but build is not working..

I tried, 
$ python3 scripts/cpu/build.py

<img width="670" alt="image" src="https://github.com/user-attachments/assets/beff16b6-cde8-4f34-aeec-6ff95ae9b5cc">

And the error msg says, "No such file or directory: 'rustup'".

I didn't implement anything on project2, should I implement "todo" blocks and retry this? 

Thank you.

**Comment by minseongg** [comment]
Could you please run the below command in the development server and then try again?

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

**Comment by minseongg** [comment]
Hmm.. it's strange. Could you please make a new workspace with "cs492-uarch" template and then try again?

**Comment by ki6090** [comment]
Okay, I will try again and let you know. Thank you.

**Comment by ki6090** [comment]
I created new workspace and tried, but it is same ,,,

**Comment by minseongg** [comment]
Could you please follow these steps in the new workspace?

1. Run `rm -rf .rustup .cargo` in the `/home/ubuntu` directory.
2. Run `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`. If it asks you to select the installation option, just press ENTER (default option).
3. Restart the terminal.
4. Run `python3 scripts/cpu/build.py` in your hazardflow directory.

**Comment by ki6090** [comment]
It works! Thanks for kind answering :)
