### ISSUE TITLE
Re-implementation of "attach_resolver" via existing combinators

### ISSUE THREAD

**Issue by JongyCysec** [kaist-cp/cs492-uarch#19]
@minseongg 

I'm worried that consecutive, minor questions may bother you.

# Question 1. 
In my understanding, overall structure of ```attach_resolver(m)``` wrapper is like below.
![image](https://github.com/user-attachments/assets/7da0c6a9-7197-49b5-a586-a376ec07cb4c)

Then, the structure above seems similar to combination of ```lfork``` and ```join```.
So, I wonder we can reuse ```lfork``` combinator and ```join``` combinator to implement ```attah_resolver``` wrapper.

It seems ```lfork_uni``` function may work since it forks ingress interface into two egress interfaces where resolver type of them are ```H::R``` and ```()```. 

However, in actual implementation, ```attach_resolver``` is implemented by two consecutive ```fsm``` combinator.
So I suspect that the reason why ```lfork``` & ```join``` combinators are not used in ```attach_resolver``` is that we need unnecessary transfer of payload of ingress interface into individual forked egress interfaces. 

# Question 2. 

I've sketched simple structure of fetch submodules and interfaces as below. 
Specifying each types of payload and resolver between modules may be helpful to understand the structure. 
So can I ask you to check whether it is right or wrong. 

![image](https://github.com/user-attachments/assets/6b322e1e-650d-4dda-866c-446e82a8e80c)

_Originally posted by @JongyCysec in https://github.com/kaist-cp/cs492-uarch/issues/16#issuecomment-2378406987_

**Comment by minseongg** [comment]
Closing, feel free to reopen if you have further questions!
