### ISSUE TITLE
Container creation issue

### ISSUE THREAD

**Issue by seo-rii** [kaist-cp/cs492-uarch#22]
Hello!

There is a problem while creating container in cloud.fearless.systems .

20220484/uarch-container
```
Error: process "/bin/sh -c conda install -n base conda-libmamba-solver conda-lock==1.4.0 &&     conda config --set solver libmamba &&     mkdir -p /opt/tools/chipyard &&     cd /opt/tools &&     git clone https://github.com/ucb-bar/chipyard.git &&     cd chipyard &&     git checkout 1.9.1 &&     ./build-setup.sh riscv-tools -s 5 -s 6 -s 7 -s 8 -s 9" did not complete successfully: exit code: 1

on main.tf line 176, in resource "docker_image" "main":
  176: resource "docker_image" "main" {
```

Can you please inspect this problem?

Thank you.

**Comment by minseongg** [comment]
We have checked that there is a version issue in the container, we will fix it ASAP and then notice to you.

Sorry for the inconvenience.

**Comment by minseongg** [comment]
We have fixed the problem. Could you please try again?

**Comment by seo-rii** [comment]
It works now! Thank you.

**Comment by seo-rii** [comment]
@minseongg I can find cs431 folder after creating container, and it seems that it includes assignment solution of it. 

Is it intended?

<img width="2056" alt="스크린샷 2024-10-03 오전 2 51 33" src="https://github.com/user-attachments/assets/f8813d9d-46f0-4ef8-9964-a85059c1781b">

**Comment by minseongg** [comment]
Have you previously taken the CS431 course? And is the assignment solution written by you?

Since the containers provided in cs431 and this course share the home directory, if you used the development server in that course, the files might still be there.
