### ISSUE TITLE
[Assignment 2] gg does not grade my solution

### ISSUE THREAD

**Issue by kingdoctor123** [kaist-cp/cs492-uarch#27]
Hello

I have the same problem as https://github.com/kaist-cp/cs492-uarch/issues/11 on the assignment 2.
I only see the below when I submit my solution.
```
===== SETUP =====

===== CHECK =====
[2024-10-06 00:06:56,426: WARNING/ForkPoolWorker-128] Demoting to runner...
Successfully submitted!
```

Can you take a look at it?
Thank you in advance.

**Comment by minseongg** [comment]
Thanks, we added the grading script for assignment 2!

Note that if the "VALID?" is "Yes", it means you have passed the Correctness and Performance tests.

To get a full score, please ensure that **you have also passed the Synthesis and PnR test on your development server**. We will do Synthesis and PnR test offline in batches after the deadline.
