### ISSUE TITLE
Are bit operations not supported in Hazardflow?

### ISSUE THREAD

**Issue by kingdoctor123** [kaist-cp/cs492-uarch#28]
Hello

I ran into strange problem when doing assignment 2.
It seems bit operations do not work as I expect in Hazardflow.

Wrong attempt (does not pass performance test by `python3 scripts/cpu/bench_test.py cpi --bp`):
```rust
let idx: u32 = (pc >> 2) & (1 << 5 - 1);
```
If I use bit operations to get an index to a table, then surprisingly performance test fails.
I confirmed that strange behavior actually occurs by manually inspecting the log file.
(e.g. misprediction on pc=0x8000008c affects prediction on pc=0x800000c4, but these addresses should be mapped to different indices on branch history table)

My fix:
```rust
let idx: u32 = (pc / 4) % 32;
```
This works.

For later assignments, can you tell me which operations are safe to use and which are not?
Thank you in advance.

**Comment by minseongg** [comment]
Hmm.. that's very strange. There might be an issue with the compiler. Sorry for the inconvenience.

Could you please send the `hw2.zip` file where the error occurred to minseong.jang@kaist.ac.kr?

**Comment by kingdoctor123** [comment]
I just noticed that it was my fault, not hazardflow's fault. I misunderstood the operator precedence between "<<" and "-". Sorry for confusion.
