### ISSUE TITLE
[Assignment 2] Question about FnOnce of "imem" and "dmem".

### ISSUE THREAD

**Issue by ki6090** [kaist-cp/cs492-uarch#29]
Hello, i am modifying a IMEM module to expand the payload with "attach_payload()" function which takes FnOnce function as an argument. So, I am wondering about FnOnce in rust. 

In riscv32_5stage.rs, there are "FnOnce" trait which are "imem" and "dmem". 
To find a references of "core()" function, there is no information about its arguments, so I wrote two questions about this.  

1. Why do we have to use "FnOnce" in instruction and data memory ("imem" and "dmem")? 
2. And how "FnOnce" can attach the payload in IMEM module without any resolver/payload data? 

Thank you.

**Comment by minseongg** [comment]
### Answer to Question 1:

In Rust, the [`FnOnce` trait](https://doc.rust-lang.org/stable/std/ops/trait.FnOnce.html) is automatically implemented for types that can be called once. For example, the primitive function `fn(I) -> E` and closures that might consume captured variables (`|i: I| -> E { .. }`) implements `FnOnce(I) -> E` trait.

And in HazardFlow, we consider a function that implements the `impl FnOnce(I) -> E` trait where `I` and `E` implement the `Interface` trait as a module with `I` as its ingress interface and `E` as its egress interface.

<p align="center">
  <img src="https://github.com/user-attachments/assets/c7e3c34b-91e3-4acf-8066-b6d169a66424" width=40% />
</p>

Therefore, both `imem` and `dmem` implement the `FnOnce(Vr<MemReq>) -> Vr<MemRespWithAddr>`, indicating that they are modules with `Vr<MemReq>` as their ingress interface and `Vr<MemRespWithAddr>` as their egress interface.

The high-level structure is as follows:

<p align="center">
  <img src="https://github.com/user-attachments/assets/4e9379f2-6c40-4845-ba8e-6c9bf174bc9c" width=55% />
</p>

### Answer to Question 2:

The `attach_payload` function takes an `m: impl FnOnce(Vr<P>) -> Vr<EP>` as a parameter and returns a new function that implements `impl FnOnce(Vr<(P, AP)>) -> Vr<(EP, AP)>`. Based on the understanding above, we can interpret `attach_payload` as a function that takes a module `m` with `Vr<P>` as its ingress interface and `Vr<EP>` as its egress interface, and returns a new module `m'` with `Vr<(P, AP)>` as its ingress interface and `Vr<(EP, AP)>` as its egress interface.

In the `attach_payload`, the module `m'` is constructed using a closure with the following structure ([code](https://github.com/kaist-cp/hazardflow/blob/main/hazardflow-designs/src/std/valid_ready/mod.rs#L103-L111)):

<p align="center">
  <img src="https://github.com/user-attachments/assets/82152c50-6108-4d84-9a8f-a254310a61ea" width=80% />
</p>

Now, you can use `attach_payload` as follows. Suppose you have an interface `i` of type `Vr<(MemReq, P)>`, where `P` represents a branch predictor update signal in assignment 2. You can then combine IMEM to `i` using `i.comb(attach_payload(imem))`.

**Comment by ki6090** [comment]
Thanks for answering. So, I understand that I have to make a module to attach the payload. Is it right?

**Comment by minseongg** [comment]
Yes! And you can make a new module by applying `attach_payload` to existing IMEM module.

**Comment by ki6090** [comment]
Thank you very much!
