### ISSUE TITLE
Lab2 Build Failure

### ISSUE THREAD

**Issue by JongyCysec** [kaist-cp/cs492-uarch#30]
When I build pipelined cpu with below commands, 
```cargo run --release -- --target core --deadcode --wire-cache --merge --system-task```

I got error 
```
thread 'rustc' panicked at hazardflow/src/compiler/pure/function.rs:1066:40:
not yet implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: Hazardflow has paniced!
```

This error is not presented when building without any code changes to skeleton code.
But it occurred when I modify the code to implement branch predictor.

When I've investigated the location of build error, it seems that the error is related to failure of compiling assignment statement.
Then, do I have to refrain from using assignment statement in my own implementation?

**Comment by minseongg** [comment]
Oh yes, that's correct. Currently, the HazardFlow compiler throws a compilation error if there is a mutable variable in the application-specific logic. Could you please modify the code to remove the mutable variables?

For example:

1. Declare a new variable when trying to assign `rhs` to `lhs`.

- Before:

```rust
let mut a;
a = b;
a = a + 1;
```

- After:

```rust
let a = b;
let a = a + 1;
```

2. Use [`set`](https://kaist-cp.github.io/hazardflow/docs/hazardflow_designs/std/value/struct.Array.html#method.set) API when trying to change an element of `lhs`.

- Before:

```rust
arr[idx] = ele;
```

- After:

```rust
let arr = arr.set(idx, ele);
```

Sorry for the inconvenience. We will include about this in the explanation.
