### ISSUE TITLE
Question about attendance

### ISSUE THREAD

**Issue by Mysigyeong** [kaist-cp/cs492-uarch#31]
Hi, I'm Byeongsu Woo, one of the class attendees.

I have to attend a conference next week (10/14 ~ 10/18), so I cannot participate in the class next week.
Is there anything that I have to do related to this issue?

**Comment by minseongg** [comment]
After discussing with the professor, we have decided that attendance at the conference will not be approved as an official absence.

But don't worry about the grade! The attendance policy for this course is not so tight.

Also, You don’t need to submit any documents for verification.

**Comment by Mysigyeong** [comment]
I got it. Thank you so much.
