### ISSUE TITLE
[Assigment2] Hazardflow Panic error when used clog2() function

### ISSUE THREAD

**Issue by ki6090** [kaist-cp/cs492-uarch#32]
Hello, I changed my logic to ```clog2()```  to calculate required bits to access branch target buffer and history table. 

And when I build this,, it gives an error with ```hazardflow paniced```. 

Is it allowed to use ```clog2()``` function in utils.rs?

Thank you.

**Comment by JongyCysec** [comment]
I've posted similar build failure question now.
I think some parts of compiler is not fully implemented. 
https://github.com/kaist-cp/cs492-uarch/issues/33#issue-2571990970

**Comment by minseongg** [comment]
Could you please check https://github.com/kaist-cp/cs492-uarch/issues/33#issuecomment-2398793742?

**Comment by ki6090** [comment]
Thank you.
