### ISSUE TITLE
[LAB2] About branch update order in M4(fetch)

### ISSUE THREAD

**Issue by JongyCysec** [kaist-cp/cs492-uarch#35]
In the module M4(fsm_map) of fetch stage, two tasks are executed.
(1) Branch prediction result created (-> forwarded to exe)
(2) Update branch predictor

Then, I wonder which order is performance-effective or desirable between (1) ->(2) and (2) -> (1).
In other words, which state do we have to consider while creating branch-prediction-result?
Previous state or Updated state from (2)?

Firstly, I describe two scenarios below in order to verify whether the order of (1) & (2) makes difference or not.

## Scenario 1 : two consecutive branch instructions ```Br1(predicted as Taken, but should not be taken. pc1)``` and ```Br2(pc1+4)```. 

Then, exe stage will send redirect to ```pc1 + 4``` which points to the instruction ```Br2```. 
And exe stage will also send update signal of ```Br1```.

In this case, the order of (1) & (2) does not matter.
That is because, difference between ```Br1``` & ```Br2``` is just 4 (different indexing into branch predictor table).
So, branch-predictor-update(```Br1```) will not influence branch-prediction-result(```Br2```) regardless of the order of (1) & (2).

## Scenario 2 : ```JalR1(predicted as not taken, but should be taken, pc1)``` -> jump -> ```JalR2(pc2)```

Exe stage will send redirect to ```JalR2``` and update signal of ```JalR1```.
In this case, assume that  index (into branch predictor table) of ```pc1(JalR1)``` and ```pc2(JalR2)``` are equivalent so they collide.
Then, branch-predictor-update(```JalR1```) will influence branch-prediction-result(```JalR2```) if (2) update happens before (1).
So, the order of (1) & (2) in M4 matters.

# Expectation
Although, the order of (1) & (2) in module M4 matters, 
(1) It is not certain that which order is more desirable since it depends on specific behavior of workloads.
(2) It will not cause significant performance difference in my expectation since ```case2``` is rare.
     (so, it will not influence the performance test of lab2)

It would be very helpful if some other students or TAs check whether such consideration, scenario, and expectation make sense or not.

**Comment by minseongg** [comment]
Wow.. Yes, you're right.

So, if two branch or JALR instructions are adjacent in program order and share the same index in the BHT or BTB, the trace of the PC leaving the fetch stage could change depending on the order of (1) and (2).

Furthermore, I believe that the order of (1) and (2) matters when `Br1` should be taken and jumped to `Br2`, but is mispredicted as not taken, and `Br2` shares the same BHT index as `Br1` (similar to Scenario 1).

```text
Br1 # should be taken and jumped to `Br2`, but the current counter is "Weakly Not Taken"

...

Br2 # shares the same BHT index as `Br1`
```

We have confirmed that this situation does not occur in the testbench used for our assignment. Therefore, let's assume that the order within a cycle is to (1) perform branch prediction and then (2) update the branch predictor.
