### ISSUE TITLE
How can I handle the error when using "attach_payload" ?

### ISSUE THREAD

**Issue by ki6090** [kaist-cp/cs492-uarch#38]
```
pub fn attacher (input: I<VrH<MemRespWithAddr, (HOption<FetEP>, DecR)>, { Dep::Helpful }>) -> I<VrH<(MemRespWithAddr, BpUpdate), (HOption<FetEP>, DecR)>, { Dep::Helpful }> {
    // Source Code
}

```
This is the brief function when I used as an argument of attach_payload. 

But the compiler said, 
<img width="975" alt="image" src="https://github.com/user-attachments/assets/b36b5bcb-b3bf-4f8a-828c-929e9e30dd5e">

I am struggling with this error for a long time because I am not familiar with rust,, so could anyone help me? 

Thank you.

**Comment by JongyCysec** [comment]
I think you're going to attach resolver & payload.

In your implementation, you've tried to attach resolver ```(HOption<FetEP>, DecR)``` and attach payload by using ```attach_payload```. 

However, ```attach_payload``` signature implies that resolver type of its input & output interface should empty, i.e. ```()```. 
( But resolver type of ```attacher``` is not ```()```)
So, I think you need to use ```attach_payload``` first in order to attach ```BpUpdate```.

And then, you can attach resolver ```(HOption<FetEP>, DecR)``` by using similar helper function ```attach_resolver```.

**Comment by minseongg** [comment]
@JongyCysec has already provided a great answer, let me give some more explanation how the `attach_resolver` module combinator is used in the baseline CPU, and some hint for the assignment 2.

In the baseline CPU, the type of `imem` is `impl FnOnce(Vr<MemReq>) -> Vr<MemRespWithAddr>`.

Based on the Answer 1 of https://github.com/kaist-cp/cs492-uarch/issues/29#issuecomment-2395945994, we can understand the `imem` is a module which have `Vr<MemReq>` as its ingress interface and `Vr<MemRespWithAddr>` as its egress interface:

<p align="center">
  <img src="https://github.com/user-attachments/assets/23a974c9-71cc-46ad-a9f7-ef385832ac71" width=100% />
</p>

---

How `attach_resolver` is used 

A module combinator `attach_resolver` has the following signature ([code](https://github.com/kaist-cp/hazardflow/blob/main/hazardflow-designs/src/std/valid_ready/mod.rs#L71)).

```rust
pub fn attach_resolver<P: Copy, EP: Copy, R: Copy>(
    m: impl FnOnce(Vr<P>) -> Vr<EP>,
) -> impl FnOnce(I<VrH<P, R>, { Dep::Helpful }>) -> I<VrH<EP, R>, { Dep::Helpful }>
```

In the code above, we can think of `attach_resolver` as a function that takes a module `m` and returns a new module. Each of them has such ingress/egress interfaces:

<p align="center">
  <img src="https://github.com/user-attachments/assets/ab550aae-45dd-4493-8f1b-f3567015648c" width=100% />
</p>

- Type of module `m`:
  + Ingress interface: `Vr<P>`
  + Egress interface: `Vr<EP>`
- Type of returned module `attach_resolver(m)`:
  + Ingress interface: `I<VrH<P, R>, { Dep::Helpful }>`
  + Egress interface: `I<VrH<EP, R>, { Dep::Helpful }>`

In the baseline CPU, we used `attach_resolver(imem)` to make a module that attaches an additional resolver of type `(HOption<FetEP>, DecR)` to the ingress/egress interfaces of the original `imem`.

<p align="center">
  <img src="https://github.com/user-attachments/assets/f690eb11-8cb7-4400-b770-4a90d1e961f9" width=100% />
</p>

---

And another module combinator `attach_payload` has the following signature ([code](https://github.com/kaist-cp/hazardflow/blob/main/hazardflow-designs/src/std/valid_ready/mod.rs#L100)),

```rust
pub fn attach_payload<P: Copy, EP: Copy, AP: Copy>(
    m: impl FnOnce(Vr<P>) -> Vr<EP>,
) -> impl FnOnce(Vr<(P, AP)>) -> Vr<(EP, AP)>
```

Similar as `attach_resolver`, we can think of `attach_payload` as a function that takes a module `m` and returns a new module. Each of them has such ingress/egress interfaces:

<p align="center">
  <img src="https://github.com/user-attachments/assets/a6cca9d7-5801-4a7e-9f24-9e05c43baa95" width=100% />
</p>

- Type of module `m`:
  + Ingress interface: `Vr<P>`
  + Egress interface: `Vr<EP>`
- Type of returned module `attach_payload(m)`:
  + Ingress interface: `Vr<(P, AP)>`
  + Egress interface: `Vr<(EP, AP)>`

Now, the following is the module we want to make in Assignment 2. In addition to the baseline CPU, an additional payload of type `HOption<BpUpdate>` is attached to the ingress/egress interfaces of the IMEM to carry the branch predictor update signals.

<p align="center">
  <img src="https://github.com/user-attachments/assets/41c28e32-36f9-4071-b441-433b62a9e5e2" width=100% />
</p>

I recommend you to think what should be in the `??`. And then, you can combine that module with `comb(??)`.

**Comment by ki6090** [comment]
Thanks for both answers.
To sum up, ```attach_payload()```  and ```attach_resolver``` are both using ```Vr<P> -> Vr<EP>``` module which resolver is ```()``` as a parameter. 

(According to ```pub type Vr<P, const D: Dep = { Dep::Helpful }> = I<VrH<P>, D>;``` in mod.rs)

Finally, ```attach_payload()``` returns ```Vr<P, AP>``` and ```Vr<EP, AP>``` as ingress/egress payload, and its resolver is also ```()```. 
```attach_resolver()``` returns ```I<VrH<P, R>>``` and ```I<VrH<EP, R>>``` which resolver is attached from ```()``` state. 

Is my understanding right?

Thanks for kind answers.

**Comment by minseongg** [comment]
Yes!

In precise, the `Vr<P> = I<VrH<P, ()>, { Dep::Helpful }> = I<AndH<ValidH<P, ()>>, { Dep::Helpful }>` has `Ready<()>` as the resolver signal ([book](https://kaist-cp.github.io/hazardflow/book/lang/interface.html#vrh)). Since it means valid-ready interface, it contains the ready signal, but there is no other signals for the resolver.

I believe that you just omitted the ready signal.

**Comment by ki6090** [comment]
Oh, yes I omitted that. 

Thank you very much.
