### ISSUE TITLE
attach_resolver() circuit level meaning

### ISSUE THREAD

**Issue by Coll1ns-cult** [kaist-cp/cs492-uarch#39]
attach_resolve() function has the following signature:
```rust
pub fn attach_resolver<P: Copy, EP: Copy, R: Copy, const D: Dep, const ED: Dep>(
    m: impl FnOnce(Vr<P, D>) -> Vr<EP, ED>,
) -> impl FnOnce(I<VrH<P, R>, D>) -> I<VrH<EP, R>, ED>
```
From what I understood, the attach_resolver function is a helper function that adds wires to the module ```m``` at the circuit level that supports the resolver type ```R```. Looking at the source code of attach_resolver()
```rust
pub fn attach_resolver<P: Copy, EP: Copy, R: Copy, const D: Dep, const ED: Dep>(
    m: impl FnOnce(Vr<P, D>) -> Vr<EP, ED>,
) -> impl FnOnce(I<VrH<P, R>, D>) -> I<VrH<EP, R>, ED> {
    |i: I<VrH<P, R>, D>| -> I<VrH<EP, R>, ED> {
        // TODO: Need to consider `m` need multi-cycle
       //payload is I<ValidH<P, ()>, D> (Vr<P, D>) and hazard is I<ValidH<(), R>, Dep::Helpful> 
        let (payload, hazard) = unsafe {
            //so we have a stateless FSM which has a tuple egress payload with 
            //1. Valid ready interface (there is only payload)
            //2. Custom valid ready interface (there is only resolver)
            Interface::fsm::<(Vr<P, D>, I<ValidH<(), R>, {Dep::Helpful }>), ()>(i, (), |ip, (er1, er2), s| {
                let ir = Ready::new(er1.ready, er2); //inner will be resolver of the second, and ready will be boolean again...
                let ep1 = ip; //no resolver
                let ep2 = Some(()); // no payload 
                ((ep1, ep2), ir, s)
            })
        };

        unsafe {
            (payload.comb(m), hazard).fsm::<I<VrH<EP, R>, ED>, ()>((), |(ip1, _), er, s| {
                let ir1 = er.map(|_| ());
                let ir2 = er.inner;
                let ep = ip1;
                (ep, (ir1, ir2), s)
            })
        }
    }
}
```
We use trait function fsm to generate the (payload, hazard) tuple by calling ```Interface::fsm<>()```, But I don't understand how this is represented at the circuit level. According to what I understood, normally, fsm function is called on ingress interface **types**  which has wires as input at the circuit level and FSM plays with these wires to convert them to egress interface wires at the circuit level. I don't understand calling FSM through trait, which doesn't have any input wires, and yet we get the egress interface wires.

**Comment by minseongg** [comment]
When the `Interface::fsm(self, init_state, f)` is directly used in the code, then you may consider the `self` is the ingress interface. For example, let's look into the following code:

```rust
let (payload, hazard) = unsafe {
    Interface::fsm::<(Vr<P, D>, I<ValidH<(), R>, {Dep::Helpful }>), ()>(i, (), |ip, (er1, er2), s| {
        let ir = Ready::new(er1.ready, er2); //inner will be resolver of the second, and ready will be boolean again...
        let ep1 = ip; //no resolver
        let ep2 = Some(()); // no payload 
        ((ep1, ep2), ir, s)
    })
};
```

It has the first argument `i` as its ingress interface. In circuit level, It will be compiled to the following:

<p align="center">
  <img src="https://github.com/user-attachments/assets/79b5942e-8c0f-4912-a363-b185c88f3062" width=80% />
</p>

+) The upstream repository has been updated, now it does not implemented with the generic fsm combinator ([code](https://github.com/kaist-cp/hazardflow/blob/main/hazardflow-designs/src/std/valid_ready/mod.rs#L71)). We recommend you to download the upstream!
