### ISSUE TITLE
[Assignment 1] FIR Filter (due: 10/6, 23:59:59 (KST))

### ISSUE THREAD

**Issue by minseongg** [kaist-cp/cs492-uarch#4]
Implement a FIR filter.

- Read the description [here](https://docs.google.com/document/d/1Eu4VqPes_3GpLw2OgTZvzI4XXoB_ioWwm0dIPFxqR3U/edit?usp=sharing).
- The files for assignment 1 are located in the [scripts/fir_filter](https://github.com/kaist-cp/hazardflow/tree/main/scripts/fir_filter) directory. You're going to implement [fir.v](https://github.com/kaist-cp/hazardflow/blob/main/scripts/fir_filter/fir.v).
- Submit `fir.v` to [here](https://gg.kaist.ac.kr/assignment/128/).
- **IMPORTANT**: Only the last submission will be used for grading. Please make sure the last submission passes the testbench.
- **IMPORTANT**: Don't fork the [hazardflow](https://github.com/kaist-cp/hazardflow/tree/main) repository, It'll be public!

**Comment by minseongg** [comment]
We added the grading script for assignment 1: https://github.com/kaist-cp/cs492-uarch/issues/11#issuecomment-2336745947

You can check the result with "VALID?" column in the GG.

FYI: We checked that all the previous submissions passed the grader.

**Comment by minseongg** [comment]
**IMPORTANT**: Due to some holiday break, we have not been able to cover as much material as expected, so we have decided to extend the deadline for Assignment 1 by one week.

The revised due date is 10/6, 23:59:59 (KST).

**Comment by seo-rii** [comment]
Can you please update the issue title with revised date?

**Comment by minseongg** [comment]
@seo-rii Thank you for reporting. We have changed the issue title.
