### ISSUE TITLE
[Lab3] About Branch combinator of extended ALU

### ISSUE THREAD

**Issue by JongyCysec** [kaist-cp/cs492-uarch#40]
We're recommended to use ```exclusive``` wrapper in order to ensure that exactly outgoing data is generated for each incoming data.
And example code implementation provided in the doc is as below.

```
fn exe_inner(
    i: I<VrH<DecEP, (HOption<(DecEP, u32)>, MemR)>, { Dep::Demanding }>,
) -> I<VrH<(DecEP, u32), MemR>, { Dep::Demanding }> {
    todo!("fill out logics for `reg` and extended ALU")
}

/// Execute stage.
pub fn exe(
    i: I<VrH<DecEP, ExeR>, { Dep::Demanding }>,
) -> I<VrH<ExeEP, MemR>, { Dep::Demanding }> {
    i.map_resolver_inner::<(HOption<(DecEP, u32)>, MemR)>(gen_resolver)
        .comb(exclusive(exe_inner)) // this line was changed from the existing implementation.
        .filter_map_drop_with_r_inner(|(ip, alu_out), er| gen_payload(ip, alu_out, er))
}
```

So, we need to separate ```reg``` and ```extended alu``` into ```exe_inner``` function which is wrapped by ```exclusive```.
We should use ```branch``` combinator for ```extended_alu``` in ```exe_inner```. 
However, I think ```(HOption<(DecEP, u32)>, MemR)``` does not match tuple sum of two resolvers of branches (```Base ALU``` and ```Multiplier```).

In case of ```Mem``` stage, the first ```map_resolver_inner``` combinator specifies the type of tuple sum of resolvers as below. 
```(HOption<(MemRespWithAddr, ExeEP)>, HOption<(CsrResp, ExeEP)>, (HOption<ExeEP>, WbR))```
```
pub fn mem(
    i: I<VrH<ExeEP, MemR>, { Dep::Demanding }>,
    dmem: impl FnOnce(Vr<MemReq>) -> Vr<MemRespWithAddr>,
) -> I<VrH<MemEP, WbR>, { Dep::Demanding }> {
    let exep = i
        .map_resolver_inner::<(HOption<(MemRespWithAddr, ExeEP)>, HOption<(CsrResp, ExeEP)>, (HOption<ExeEP>, WbR))>(
            gen_resolver,
        )
        .reg_fwd(true);
```

So, I think we have 2 options.
1. Add  ```map_resolver``` combinator into ```exe_inner``` so that it converts sum resolver type ```((HOption<(DecEP, u32)>, MemR), (HOption<(DecEP, u32)>, MemR))``` from branch combinator into ```(HOption<(DecEP, u32)>, MemR)```
2. Change  generic resolver type of ```map_resolver_inner``` of ```exe```

**Comment by minseongg** [comment]
Oh yes, that part was omitted in the assignment description. Sorry for the inconvenience.

You can use either of the two methods you suggested.

**Comment by minseongg** [comment]
For clarity, we have updated the figure depicting the structure of the extended execute logic.

It now includes an additional `map_resolver` (**M2**) in front of the `branch`, which selects the ALU result from either the Base ALU or the Multiplier path. Thank you!

**Comment by JongyCysec** [comment]
Thank you for your sincere answer !
