### ISSUE TITLE
Supplemental Material For Lab2&3

### ISSUE THREAD

**Issue by JongyCysec** [kaist-cp/cs492-uarch#46]
I finalize the sketch of cpu structure in this issue, just hoping you get some help from it while doing projects 2&3 in your busy schedule with preparing exams. (So, It would be nice to keep this issue open.)

### Description
- Interface is colored by **blue & red & black** (payload & resolver & Depending). I did not specify ```Ready``` resolver wrapper type and ```HOption``` payload Fwd type of ```Interface``` trait.
- If module has a meaningful internal state, then I've specified it with **green color** in module box. 
   (**ex. M4(Branch Predictor) in Fetch stage , Sink(Register File) in Wb stage, muldiv(Calculation Status) in Exe stage**)
- I've added comments for important functionalities or issues of modules/stages with **black color**. 
- I've colored the modules **yellow** that are expected to be implemented/modified by ourselves during lab 2 & 3. 
- Some interfaces and modules are wrapped by **green-colored box** that can be understood well with actual baseline code. (**ex. DecH, Exclusive, memory stage interfaces**).
- For Lab2, I've specified the **generation/reflection** routes of Branch Predictor's **prediction & update** as **pink/purple arrows** spanning fetch/decode/exe stages. (Refer to Lab2 documentation for specific information.)
### Sketch 

![hazardflow_cpu](https://github.com/user-attachments/assets/39b67a29-9e2a-4dc9-ac63-a64539cd3034)

### Link
I leave a link in case certain parts are too small to read. 
https://app.diagrams.net/#G1-Ozeu2-2i138ylAvP2cd_VND89gwboCG#%7B%22pageId%22%3A%22C0vsTpqooSxowkVAgLYY%22%7D

**Comment by nhatanh0104** [comment]
I have a question regarding the branch predictor instantiated with the 'fsm_map' combinator in the fetch stage (M4). The 'fsm_map' updates its state based on the ingress payload and the current state during the ingress transfer. Therefore, the branch predictor update signal should be passed to the ingress payload of the M4. Given this, should the egress payload of M4 be structured as (FetEP, HOption<BpUpdate>)? Or is the HOption<BpUpdate> already included within the FetEP?

Thank you in advance for your help!

**Comment by JongyCysec** [comment]
During the payload transfer from M1 to M3 of fetch stage, branch-update-signal(```BpUpdate```) is transferred as ```(u32, BpUpdate)``` type where u32 refers ```next_pc```.

However, payload type from M3 to M4 is just ```FetEP```.  It seems we omit branch update signal on the way. 
So, I suspect that your question can be summarized as "Why don't we add ```BpUpdate``` to such payload type?". 

That is because, in my implementation, I've added additional ```BpUpdate``` members into ```FetEP```.
(Also, it is noted in the documentation of assignment 2 that you might need to add additional members to ```FetEP```. You can check it.)

Therefore, M3(IMEM, map+comb+map) will generate new ```FetEP``` which contains ```BpUpdate``` signal generated from Exe stage.

According to ```Interface``` struct, ```Fwd``` signal is wrapped by ```HOption```. And normally resolver type specified in ```VrH``` is wrapped by ```Ready``` struct. However, I did not write full, complete type of interface (```HOption``` for payload and  ```Ready``` for resolver). I left it out because I thought it would make the sketch quite messy. 

***FYI: The above scheme is based on my implementation while I tried to avoid revealing too many implementation details. 
Therefore, it is not the golden-reference. It's perfectly fine to deviate from the example model above. 
I just visualized somewhat abstracted code as shown in the sketch above, hoping other students can get help from it.***

**Comment by nhatanh0104** [comment]
Thank you for your thorough response! I have gained a better understanding from it.
