### ISSUE TITLE
Server Error (500) on gg

### ISSUE THREAD

**Issue by kingdoctor123** [kaist-cp/cs492-uarch#5]
Hello,

I tried to login to the gg, but it fails due to "Server Error (500)".
Precisely, 

- With my old account (for the student ID when I was undergraduate student), I can successfully log in to the gg, but cs492 is not visible.

- With my new account (for the student ID that I'm now using), I suffer from "Server Error (500)".

- This error occurs on various devices (tested on my labtop, desktop, ipad, and mobile phone (connected by cellular network)).

Thank you in advance.

**Comment by jeehoonkang** [comment]
@kingdoctor123 try again?

**Comment by JongyCysec** [comment]
I have a similar problem with gg website. And while workspace build, docker image failed to be built in development server too.

**Comment by JongyCysec** [comment]
I have same "Server Error(500)" response from gg website.

And, while establishing workspace in development server, it raised an error with docker image build.

**Comment by woojinnn** [comment]
@JongyCysec Regarding the development server: Could you try it again? We made some update last night, and I think other student's workspaces are built well.

**Comment by JongyCysec** [comment]
@woojinnn Trying it again, I succeed to build workspace well. Thank you

**Comment by kingdoctor123** [comment]
> @kingdoctor123 try again?

@jeehoonkang Now it works. Thank you

**Comment by jeehoonkang** [comment]
@JongyCysec please send me an email with your student ids (including old ones if exist)

**Comment by jeehoonkang** [comment]
Will handle all login problems on Saturday.
