### ISSUE TITLE
About ```Regfile``` and ```bypass_from_*``` members of Resolver type (```WbR```, ```MemR```, ```ExeR```)

### ISSUE THREAD

**Issue by JongyCysec** [kaist-cp/cs492-uarch#50]
# Question

When decode stage fetches value of register for its source registers, it refers to ```bypass_from_*``` members and ```Regfile```.
The ```Regfile``` in WbR is passed from Wb stage .
And Mem & Exe stage attaches its additional bypass value in ```MemR``` and ```ExeR```.

Can I ask the motivation of design choice that the code attaches additional ```bypass_from_*``` members into its Resolver instead of updating ```Regfile``` passed from Wb stage?

It is commented that decode stage priorities bypass value (Exe > Mem > Wb).
However, considering the overwrite order of Regfile (Wb -> Mem -> Exe), decode stage 's priority will not be changed.
So, decode stage can just refer to up-to-date Regfile and it don't have to look up bypass value.

# Code Modification
I've tried to change the Files ```decode.rs```, ```exe.rs```, ```mem.rs``` ```wb.rs``` as below so that each ```bypass_from_*``` is reflected into ```Regfile``` instead of being transferred.

**1. wb.rs**
```rust
#[derive(Debug, Clone, Copy, Default)]
pub struct WbR {
    ///pub bypass_from_wb: HOption<Register>, 

    /// Register file.
    pub rf: Regfile,
}

impl WbR {
    /// Creates a new writeback register.
    pub fn new(bypass_from_wb: HOption<Register>, rf: Regfile) -> Self {
        let updated_rf = match bypass_from_wb {
              Some(r) => rf.set(r.addr, r.data),
              None => rf,
        }
        Self { rf: updated_rf }
    }
}
```

- ```bypass_from_wb``` member is commented out from ```WbR```. And it is reflected into ```updated_rf``` by ```new``` function of ```WbR```

**2. mem.rs**
```rust
#[derive(Debug, Clone, Copy)]
pub struct MemR {
    /// pub bypass_from_mem: HOption<Register>,

    /// pub bypass_from_wb: HOption<Register>,

    /// Indicates that the pipeline should be redirected.
    pub redirect: HOption<u32>,

    /// Register file.
    pub rf: Regfile,
}

impl MemR {
    /// Creates a new memory resolver.
    pub fn new(wbr: WbR, bypass_from_mem: HOption<Register>, redirect: HOption<u32>) -> Self {
        let updated_rf = match bypass_from_mem {
              Some(r) => wbr.rf.set(r.addr, r.data),
              None => wbr.rf,
        }
        Self { redirect, rf: updated_rf}
    }
}
```
- ```bypass_from_mem``` & ```bypass_from_wb``` members are commented out from ```MemR```. And ```bypass_from_mem``` is reflected into ```updated_rf``` by ```new``` function of ```MemR```. 

**3. exe.rs**
```rust
#[derive(Debug, Clone, Copy)]
pub struct ExeR {
    /// pub bypass_from_exe: HOption<Register>,

    /// pub bypass_from_mem: HOption<Register>,

    /// pub bypass_from_wb: HOption<Register>,

    /// It contains the rd address of load or CSR instructions.
    pub stall: HOption<U<{ clog2(REGS) }>>,

    /// Indicates that the pipeline should be redirected.
    pub redirect: HOption<u32>,

    /// Register file.
    pub rf: Regfile,
}

impl ExeR {
    /// Creates a new execute resolver.
    pub fn new(
        memr: MemR,
        bypass: HOption<Register>,
        stall: HOption<U<{ clog2(REGS) }>>,
        redirect: HOption<u32>,
    ) -> Self {
        let updated_rf = match bypass {
             Some(r) => mem.rf.set(r.addr, r.data),
             None => mem.rf,
        }
        Self {
            stall,
            redirect: memr.redirect.or(redirect),
            rf: updated_rf,
        }
    }
}
```
- ```bypass_from_exe``` , ```bypass_from_mem```, ```bypass_from_wb``` members are commented out from ```ExeR```. And ```bypass_from_exe``` is reflected into ```updated_rf``` by ```new``` function of ```ExeR```. 

**4.decode.rs**
```rust
fn gen_payload(ip: FetEP, inst: Instruction, er: ExeR) -> HOption<DecEP> {
    if er.redirect.is_some() {
        return None;
    }

    let rs1_addr = inst.rs1_addr;
    let rs2_addr = inst.rs2_addr;

    let bypass = |addr: U<{ clog2(REGS) }>| -> u32 {
        // Check that the data can be bypassed.
        // let from_exe = er.bypass_from_exe.filter(|r| addr == r.addr).map(|r| r.data);
        // let from_mem = er.bypass_from_mem.filter(|r| addr == r.addr).map(|r| r.data);
        // let from_wb = er.bypass_from_wb.filter(|r| addr == r.addr).map(|r| r.data);

        // Bypassing priority: EXE > MEM > WB
        // from_exe.or(from_mem).or(from_wb).unwrap_or(er.rf[addr])
        er.rf[addr]
    };

    ...
}
```
- ```bypass``` closure in ```gen_payload``` function of ```decode.rs``` does not consider ```bypass_from_*``` members anymore. 
- Instead, it just fetches value of source registers from up-to-date ```Regfile```. 

# Testing
In order to check whether such modified design works well or not, I 've tested ```isa_test(base, mext)``` and ```bench_test```. 
And it works well for such test cases.

If some stage requires the specific address of bypassed register, it would be problematic since bypass register value is consumed into register file. 

So I'm worried that it will adversely affect the code that will be added in the future.

**Comment by minseongg** [comment]
Good catch! It seems your modification simplifies the logic and may reduce area usage.

Actually, the motivation for including `bypass_from_*` fields in the resolver structs is just for debugging purpose. When debugging misbehave waveform file, it can be helpful to see the entire (address, data) pairs for bypass signals from later stages.

So, if you pass all the test cases, then you can consider your code is more optimized version of the baseline implementation.

**Comment by JongyCysec** [comment]
@minseongg 
Thank you for your sincere inspection !!
