### ISSUE TITLE
Next PC calculation in M1 module of Fetch Stage

### ISSUE THREAD

**Issue by Coll1ns-cult** [kaist-cp/cs492-uarch#52]
Hi,

<img width="799" alt="Screenshot 2024-10-29 at 11 10 02 PM" src="https://github.com/user-attachments/assets/34aba4f3-6e86-4dbb-aee6-e5fdb7d564ae">
Here current_pc is u32, while imm is Array<bool, 32> . I wonder how we are supposed to perform addition operation. 

Thanks in Advance!

**Comment by JongyCysec** [comment]
You may be able to convert the type from ```Array``` to ```u32``` by using ```into``` or ```from``` trait.
However, it is said in the documentation that code implementation using ```into``` trait is not successfully compiled. 
(https://github.com/kaist-cp/cs492-uarch/issues/9#issuecomment-2398802840)

So you can use ```from``` trait as below.
```
e.x. let next_pc = u32::from(some_array_data_type);
```
