### ISSUE TITLE
Server will down from November 3rd, 1:00 AM ~ 6:00 PM.

### ISSUE THREAD

**Issue by minseongg** [kaist-cp/cs492-uarch#55]
Due to the power outage of the school tomorrow, the server will be down from 1:00 AM ~ 6:00PM

We will post another announcement once the server is back up.

**Comment by JustinKim98** [comment]
Will our work saved on the server preserved?

**Comment by minseongg** [comment]
@JustinKim98 Yes, it will be preserved. The server is now backed up.
