### ISSUE TITLE
[Assignment2] Question about submission

### ISSUE THREAD

**Issue by ki6090** [kaist-cp/cs492-uarch#56]
Hello, I am working on a assignment 2. 

<img width="430" alt="image" src="https://github.com/user-attachments/assets/18dcc335-6cd0-4e0e-b41f-52eade9bbb26">

I modified another files which is not mentioned in the assignment2 direction.
Could I only modify the mentioned files in the direction? 

Thank you.

**Comment by minseongg** [comment]
Could you please provide more details on the modified file?

For example, does your modified file included in the standard library (`std`)? Or in the CPU design (`cpu`)?

If it’s included in the part of the CPU design, does it affect other stages, such as memory or writeback stages?

**Comment by ki6090** [comment]
I only modified one file which is in **cpu/branch_predictor/mod.rs**. 
This file is not mentioned in the instruction of assignment 2. 
Thank you!

**Comment by minseongg** [comment]
We have updated the submission script to include `branch_predictor/mod.rs` for grading (https://github.com/kaist-cp/hazardflow/commit/9cf6d01d4eb8e479d0802356b19b3cfdbe06dd53).

Please update to the latest version from the upstream!

**Comment by ki6090** [comment]
I checked the updated version. Thank you very much.
