### ISSUE TITLE
[Assignment2] Question about stalls in CSR instructions 

### ISSUE THREAD

**Issue by ki6090** [kaist-cp/cs492-uarch#57]
Hello, I have a question about stalls and CSR instructions. 

```
80000080:	3002a073          	csrs	mstatus,t0
80000084:	00100293          	li	t0,1
```

This is the instructions which is the part of ```coremark.dump```. 
```
[9619] retire=[1] pc=[80000080] inst=[3002a073]
[9620] retire=[0]
[9621] retire=[1] pc=[80000084] inst=[00100293] write=[r 5=00000001]
````

And this is the correct execution which is in ```logs/output/baseline/```. 

```
[9619] retire=[1] pc=[80000080] inst=[3002a073]
[9620] retire=[1] pc=[80000084] inst=[00100293] write=[r 5=00000001]
```

And this is my implementation results. 

The load-use case is appropriately covered with stalls. But only CSR instructions are not covered with stalls, so i failed on CPI tests. 

```ruby
let stall = p.and_then(|(p, _)| {
        p.wb_info.and_then(|(addr, wb_sel)| if matches!(wb_sel, WbSel::Mem | WbSel::Csr) { Some(addr) } else { None })
    });
```
This is the source code in execution stage which generates ```stall``` resolver signal to inform that the ahead instruction is CSR or accessing memory instructions in decode stage. 

```ruby
impl Hazard for DecH {
    type P = (FetEP, Instruction);
    type R = ExeR;

    fn ready((_, inst): (FetEP, Instruction), exer: ExeR) -> bool {
        let rs1_addr = inst.rs1_addr;
        let rs2_addr = inst.rs2_addr;

        // Stalled from load-use or CSR.
        let stall = exer.stall.is_some_and(|addr| rs1_addr == Some(addr) || rs2_addr == Some(addr));

        exer.redirect.is_some() || !stall
    }
}
```
And this is the source code(not modified) in ```decode.rs```. In decode stage, it decides whether stall is needed or not with payload infos and resolver signals from execution stage. 

I have two questions about this code. 

1) In source code it is ready when ```exer.redirect.is_some() || !stall```. Should we have to change the logic to ```exer.redirect.is_none() && !stall```? Because the redirection only occurs when branch misprediction or exception happens. 
If I change the logic to the mentioned code, many correctness test cases are failed. 

2) If I use the original version, how can I cover the CSR instructions to make a stall when next instruction shares the same register? 

**I appreciate your support. 
Thanks for reading.**

**Comment by minseongg** [comment]
Oh... I'm really sorry, it seems there was a bug in the provided output file.

Actually for the provided instructions, it is right that the correct execution is as follows (same as your implementation):

```
[9619] retire=[1] pc=[80000080] inst=[3002a073]
[9620] retire=[1] pc=[80000084] inst=[00100293] write=[r 5=00000001]
```

It is because there is no RAW hazard between `csrs` instruction and `li` instruction.

- `csrs mstatus, t0`: destination register is `t0`.
- `li t0, 1`: no source registers.

We will update the provided output file ASAP. Really sorry for the confusion.

**Comment by minseongg** [comment]
We have updated the CPU benchmark output: https://github.com/kaist-cp/hazardflow/commit/21aba5e97bd61b65d1405891925a82ac7e74ebd3, please check the updated upstream.

Once again, I am really sorry for the confusion caused by the incorrectly provided files.

**Comment by ki6090** [comment]
Oh, I see. I will check the updated files. Thank you!

**Comment by ki6090** [comment]
<img width="1496" alt="image" src="https://github.com/user-attachments/assets/0ddf45cc-23a5-40fb-ab08-9bcd28101791">

The instructions are too long, so checked the last part of each ```aes.txt``` file. 
<img width="913" alt="image" src="https://github.com/user-attachments/assets/b7b28cd0-b3b6-410a-8a6f-4dba750c2827">
<img width="1212" alt="image" src="https://github.com/user-attachments/assets/b3d665e6-04b8-4203-bc94-9175c6c566c4">

It seems like same after updated version, but CPI test is failed again,, 
The correctness test is all passed. 
Could I ask about the suspected bug in my code..? Thank you very much.

**Comment by ki6090** [comment]
Yes! I built the whole code and ran the test.

**Comment by ki6090** [comment]
Oh, I'm sorry. I did not checked the bp directory.. That file was without branch prediction
Sorry about that,,

**Comment by minseongg** [comment]
Oh, I see! I recommend you to compare difference between the log files in `scripts/cpu/logs/output/bp` and `scripts/cpu/output`.
