### ISSUE TITLE
Test result of Lab4(pe)

### ISSUE THREAD

**Issue by JongyCysec** [kaist-cp/cs492-uarch#61]
It is said in the documentation that **"If each testbench completes without an error message, it means you have passed the test."**

Please forgive me for double-checking the my output results.

The result of last few lines of messages in terminal I got from testing `matrix_add`, `matmul`, `conv`, `raw_hazard` are as below.

### matrix_add
<img width="1370" alt="matrix_add" src="https://github.com/user-attachments/assets/9ae83f5e-f294-454c-9b76-90df52b38cfe">

### matmul
<img width="694" alt="matmul" src="https://github.com/user-attachments/assets/940b6845-6f06-432e-a68c-3cd21cac0de7">

### conv
<img width="839" alt="conv" src="https://github.com/user-attachments/assets/4317bd97-2ed8-4b2e-86ec-3e03a18b2c3c">

### raw_hazard

<img width="743" alt="raw_hazard" src="https://github.com/user-attachments/assets/3b0340f6-8d68-4d02-b042-2e68e18d6bc3">

Can I request you to check whether such outputs are valid or not?

**Comment by minseongg** [comment]
Yes, you have passed all the test cases. Congratulations!

**Comment by JongyCysec** [comment]
@minseongg 
 Thank you for taking the time to respond to my insignificant requests !!
