### ISSUE TITLE
CS492 does not appear on my gg account

### ISSUE THREAD

**Issue by hongkim9815** [kaist-cp/cs492-uarch#7]
Hello,

I already have an account on the GG site from taking the CS431 course previously. However, I’m currently experiencing an issue that the CS492 course is not appearing, while CS431 is still visible.

Could you please assist in resolving this issue? My email address is hongkim9815@kaist.ac.kr.

Thank you.

**Comment by jeehoonkang** [comment]
@hongkim9815 try again?

**Comment by jeehoonkang** [comment]
Will handle all login problems on Saturday.

**Comment by hongkim9815** [comment]
It works fine! Sorry for late reply... Have a good day!
