### ISSUE TITLE
[Hazardflow doc] Question about type of ingress resolver of `transparent_fifo` in Fifo tutorial.

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs492-uarch#70]
In the [module description for fifo](https://kaist-cp.github.io/hazardflow/book/tutorial/custom_fifo.html#modular-design), the type of ingress resolver for `transparent_fifo` is `Ready<((),FifoS)>`. 
Why is the resolver type a pair of unit and `FifoS`? Can't it just be FifoS, as unit types encode no information?

**Comment by Lee-Janggun** [comment]
Also, `VrH` is used here but [defined later](https://kaist-cp.github.io/hazardflow/book/lang/interface.html#vrh). Might be better to give it a forward reference.

**Comment by JongyCysec** [comment]
My answer might be ambiguous and not be correct. But I hope it will help you.

In the sketch of modular design of fifo, it seems additional empty type in resolver is useless. 

When examining the combinators in baseline code, you can check that the combinators whose function name start with ```transparent``` generates its states into ingress resolver type. 
( At the beginning of the class, such prefix name was ```naked```. I think TA have decided to change its name from ```naked``` to ```transparent. You can check ```reg```, ```fifo```, ```fsm_map``` combinators with ```transparent``` prefix. )

So, in general case, ```transparent_fifo``` will generate ```Ready<R, FifoS<P,N>)>``` from egress resolver type ```Ready<R>```.

**Comment by minseongg** [comment]
### About `transparent_fifo`:

The `transparent_fifo` combinator has the following signature ([rustdoc](https://kaist-cp.github.io/hazardflow/docs/hazardflow_designs/std/hazard/struct.I.html#method.transparent_fifo)):

<p align="center">
  <img src="https://github.com/user-attachments/assets/395db386-6ded-4c4d-8f66-e0bb4ee20012" width=60% />
</p>

- Ingress interface: `I<VrH<P, (R, FifoS<P, N>)>, D>`
- Egress interface: `I<VrH<P, R>, { Dep::Helpful }>`

It is designed to accept arbitrary resolver signal (of type `R`) from the egress side, and in the tutorial, `R` is set to `()`. As you mentioned, it has no information and is used only to match the IO type of the combinator.

To address this problem, I think we could define a specialized version of the `transparent_fifo` that takes `I<VrH<P, FifoS>>` and returns `Vr<P>`. We will update the code and documentation and then notify to you. Thank you.

### About `VrH`:

We will add forward reference. Thank you.

**Comment by Lee-Janggun** [comment]
Thanks for the clear explanations!

**Comment by minseongg** [comment]
We have updated the code and the documentation:

- Define `transparent_fifo` with valid-ready egress interface: https://github.com/kaist-cp/hazardflow/commit/11c1619dc849f87e9818b24e7658a34c738a7fb3
- Add forward reference for `VrH`: https://github.com/kaist-cp/hazardflow/commit/f453a2bdce3223a932985b4a8457ac0017bf85a4
