### ISSUE TITLE
[Assignment4] Submission failed after releasing assignment 6

### ISSUE THREAD

**Issue by ki6090** [kaist-cp/cs492-uarch#74]
<img width="929" alt="image" src="https://github.com/user-attachments/assets/fef826fc-035f-4241-a27b-19c1e515a115">

Hello, I resubmitted assignment4 to GG after release of assignment 6. 
Before I submitted assignment4, I passed the test. 

It seems like compile error.. 

Could you help this problem? 

Thank you very much.

**Comment by minseongg** [comment]
Oh, sorry it was due to some skeleton code changes while preparing Assignment 6.

We have nullified the previous submission, could you please rebase the latest version of the hazardflow and then submit again? I believe there is no need to change the logic.

```
$ git remote add upstream https://github.com/kaist-cp/hazardflow.git
$ git pull upstream main --rebase --autostash
```

**Comment by ki6090** [comment]
Oh, Thanks for fast response. 
The problem is solved!
