### ISSUE TITLE
[Assignment6] Hazardflow paniced error

### ISSUE THREAD

**Issue by ki6090** [kaist-cp/cs492-uarch#76]
Hello, I am working on assignment 6. I already filled all ```todo!()``` functions but the compiler has paniced due to some errors. 

How can I find the specific part of the error? 

Thank you very much.
<img width="1184" alt="image" src="https://github.com/user-attachments/assets/85729aa4-b40a-4969-a86b-6a645d5630be">

**Comment by ki6090** [comment]
Oh, I solved the problem! 
The problem was pattern matching with 

``` _ => panic!()```

Thank you!

**Comment by minseongg** [comment]
Oh, I see!

I suggest you to use `hpanic!` instead of `panic!`. We will add this to the unsupported features issue. Thank you.

**Comment by ki6090** [comment]
I will use ```hpanic!``` instead of ```panic!```. 
Thank you!!

**Comment by minseongg** [comment]
Sorry, I just found that `_ => hpanic!()` also can cause the same problem.

Instead of that, I suggest you to remove the `#![allow(warnings)]` in the `mesh_with_delays.rs` code.

**Comment by ki6090** [comment]
Thank you!! I will try it later.
