### ISSUE TITLE
[Assignment6] Meaning of error message about "Pipeline stall" in 'conv' integration test

### ISSUE THREAD

**Issue by ki6090** [kaist-cp/cs492-uarch#78]
<img width="1400" alt="image" src="https://github.com/user-attachments/assets/1a52a749-0287-43dd-89ee-8891a3a91e86">

Hello, I already passed all unit test and ```matmul```, ```matrix_add```, ```raw_hazard``` integration test. 

But only ```conv``` test fails... 

Could I get some hints about the meaning of pipeline stall error message? ,,,

Other error message shows the different results and I solved with that messages, but this message cannot figure about my code errors... 

Thanks for reading!

**Comment by JongyCysec** [comment]
Sadly, I encountered same problem too...

**Comment by woojinnn** [comment]
* After the Execute module (which is outer module of MeshWithDelays module) finishes its execution, it sends `rob_id` to reservation station module to notify that Execute module finished its execution. If Reservation station doesn't receive the fired `rob_id` more than 10000 cycles, the Reservation Station classifies it as stalled and throws an error.
* Probably your implementation isn't sending ready signal properly, and it is blocking the execution of next command. As a hint, `matmul`, `matrix_add`, and `Raw_hazard` testcases send `DIM*DIM` (where `DIM` indicates the Mesh size) matrices to MeshDelays module, whilst the `conv` testcase sends partial inputs. (For instance, `5*5` matrices, etc...) How about checking your counter management logic etc...?

**Comment by ki6090** [comment]
Thanks for kind answer!!

**Comment by minseongg** [comment]
We will prepare the reference waveform for debugging purpose ASAP. Sorry for the inconvenience.

**Comment by JongyCysec** [comment]
@woojinnn 
I've examined through sub-modules where stall can happen.
Considering the complexity of the design and hardness of debugging, it would have been quite hard for me to debug own myself without your sincere help.

Thanks to your explanation, I can solve the problem !!

**Comment by woojinnn** [comment]
@JongyCysec Congrats!
![image](https://github.com/user-attachments/assets/f34178b4-3a2a-4e00-a933-19c2f1878dc8)

**Comment by minseongg** [comment]
We have added reference waveform files for integration tests (https://github.com/kaist-cp/hazardflow/commit/53b99dd679399360a4c11b9d0b7a93063efe72a5).

For more details, please refer to https://github.com/kaist-cp/cs492-uarch/issues/71#issuecomment-2491190552!

**Comment by ki6090** [comment]
Thank you!! I appreciate your help.
