### ISSUE TITLE
gg login issue

### ISSUE THREAD

**Issue by siujeong** [kaist-cp/cs492-uarch#8]
Hello, 
I'm having the same problem as the closed issue https://github.com/kaist-cp/cs492-uarch/issues/6

I'm not receiving the password reset email. 

Thank you

**Comment by jeehoonkang** [comment]
Will handle all login problems on Saturday.

**Comment by siujeong** [comment]
It still doesn't work.

**Comment by jeehoonkang** [comment]
Would you all please try again?

**Comment by siujeong** [comment]
I still can't receive the email via my kaist email address,,

**Comment by jeehoonkang** [comment]
@siujeong please send me an email with the details on (1) what you did; (2) what you expect; and (3) what you got instead.
