### ISSUE TITLE
[Nov 27th] Video Lecture

### ISSUE THREAD

**Issue by minseongg** [kaist-cp/cs492-uarch#83]
On **November 27th (Wed)**, you will watch the video [The Future of Fast Code: Giving Hardware What It Wants](https://www.youtube.com/live/66oKqvwoIv0?feature=shared).

You don't need to come to the classroom. Thank you.

Introduction:

---

### The Future of Fast Code: Giving Hardware What It Wants

In the twilight of Moore’s Law, computer hardware has diverged from the programming models we use to control it. As a result, the performance and complexity gaps between “reasonable” programs and the fastest code are huge and growing. This talk will explore fundamental issues that drive hardware efficiency. From that foundation, it will highlight challenges and opportunities for the programming systems community in productively unlocking the potential of current and future hardware. Major themes include: leveraging domain-specific languages; balancing safety, automation, and control for high-performance programming; and broadening our understanding of “correctness” in a world of numerical programs and machine learning.

---

**Comment by JustinKim98** [comment]
Did you mean November 27th? (November 26th is Tuesday)

**Comment by minseongg** [comment]
@JustinKim98 Oh, it was a typo. Sorry for the inconvenience.
