### ISSUE TITLE
[Lecture] Information on Remaining Lectures

### ISSUE THREAD

**Issue by minseongg** [kaist-cp/cs492-uarch#84]
The remaining lectures (12/2, 12/4, 12/9, 12/11) will be conducted as follows:

- **12/2 (Mon)**: Video Lecture ([From C/C++ to Dynamically Scheduled Circuits](https://www.youtube.com/watch?v=mQU8iU0HyHw))

---

### From C/C++ to Dynamically Scheduled Circuits

High-level synthesis (HLS) tools generate digital hardware designs from high-level programming languages (e.g., C/C++) and promise to liberate designers from low-level hardware description details. Yet, HLS tools are still acceptable only for certain classes of applications and are criticized for the difficulty of extracting the desired level of performance: generating good circuits still requires tedious code restructuring and hardware design expertise. 

In this talk, Professor Lana Josipović presents a new HLS methodology that produces dynamically scheduled, dataflow circuits out of C/C++ code; the resulting circuits achieve good performance out-of-the-box and realize behaviors that are beyond the capabilities of standard HLS tools. Professor Josipović outlines mathematical models to optimize the performance and area of the resulting circuits, as well as techniques to achieve characteristics that standard HLS cannot support, such as out-of-order memory accesses and speculative execution. These contributions redefine the HLS paradigm by introducing characteristics of modern superscalar processors to hardware designs; such behaviors are key for specialized computing to be successful in new contexts and broader application domains.

---

- **12/4 (Wed)**: No class
- **12/9 (Mon)**: Offline Lecture (Homework Q&A session, attendance optional)
- **12/11 (Wed)**: Offline Lecture (Topic: AI Compiler)

More details will be announced soon. Thank you!

**Comment by minseongg** [comment]
**IMPORTANT**: Due to today(12/4)'s class cancellation, the schedule has been changed.

Please check the updated schedule. Thank you!

**Comment by seo-rii** [comment]
I can't open supplementary document [Introduction to TorchInductor](https://docs.google.com/document/d/1zY9Nlmh5jT39Q92aDYf3dHOAXh2xCMdeS6pnbX0Dqpw/edit?usp=sharing) in [Wednesday's lecture](https://docs.google.com/presentation/d/1RZdV3Z-Q1NEbpU1-qk9C97yE1QvwNLJ9Gc7JLaFLZCw/edit#slide=id.g31b5e19a3c0_1_31) because of the permission problem. Can you please check it? Thank you!

**Comment by minseongg** [comment]
@seo-rii That document is currently a work in progress and will be completed soon.

Once the work is finished, we will share it with students. Sorry for the inconvenience.

We will notify you as soon as it's ready!
