### ISSUE TITLE
[Assignment 4] Hazardflow has paniced! by not yet implemented 

### ISSUE THREAD

**Issue by ksy980418** [kaist-cp/cs492-uarch#85]
```
ubuntu@20245047:~/hazardflow$ bash scripts/gemmini/unit_test.sh pe
    Finished release [optimized] target(s) in 0.05s
     Running `target/release/hazardflow-rustc --target pe --merge --system-task`
[INFO:2024-12-02T08:00:08] <hazardflow/src/compiler/virgen.rs:164> Preprocessing "pe_top"
[INFO:2024-12-02T08:00:08] <hazardflow/src/compiler/build_submodule_graph.rs:1886> Constructing Submodule graph of pe_top
thread 'rustc' panicked at hazardflow/src/compiler/prelude.rs:346:37:
not yet implemented: ref type ReErased Foreign(
    DefId(2:9885 ~ core[6d34]::fmt::rt::{extern#0}::Opaque),
) Not
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: Hazardflow has paniced!
  |
  = note: Please report this bug over here: https://github.com/kaist-cp/hazardflow
```

**Comment by woojinnn** [comment]
Please write down what you did and what you want.

**Comment by ksy980418** [comment]
I just ran the test like above, then it paniced.

Is it normal to panic like that?

**Comment by minseongg** [comment]
It panics when there are some `todo!()`s remained in the implementation of `pe`.

Could you please check it?

+) If you have written intended `todo!()`, then I suggest you to replace it with `hpanic!()` macro.

**Comment by ksy980418** [comment]
So you mean that "thread 'rustc' panicked at hazardflow/src/compiler/prelude.rs:346:37" is because of todo!() in pe.rs??

Or should I need to implement hazardflow/src/compiler/prelude.rs:346:37 this part?

**Comment by minseongg** [comment]
> So you mean that "thread 'rustc' panicked at hazardflow/src/compiler/prelude.rs:346:37" is because of todo!() in pe.rs??

Yes, it is due to the `todo!()` in `pe.rs`.

In Assignment 4, you are required to remove the `todo!()` in the `pe` function and implement the logic for the PE. After you complete the implementation of the `pe` function, I believe that you can run the test without compiler panic.

> should I need to implement hazardflow/src/compiler/prelude.rs:346:37 this part?

No, you don't need to implement that part.
