### ISSUE TITLE
[Assignment 4] unit test failed

### ISSUE THREAD

**Issue by Unknown-Box** [kaist-cp/cs492-uarch#90]
An error occurred while running the unit test `bash scripts/gemmini/unit_test.sh pe`. It seems to be a compilation error, not a runtime error due to `todo!()`. I restarted my server, but it still happens. How can I solve it?

<img width="725" alt="스크린샷 2024-12-06 오전 12 04 45" src="https://github.com/user-attachments/assets/88dd78da-498c-44fc-b001-ff3851aa1716">

**Comment by Unknown-Box** [comment]
Oh, it was suddenly resolved. Sorry.

**Comment by minseongg** [comment]
Closing, if you meet the same error again, feel free to reopen the issue!
