### ISSUE TITLE
I can't access to GG website.

### ISSUE THREAD

**Issue by hongkim9815** [kaist-cp/cs492-uarch#91]
After I logged in to authentik, then it raises redirect error ...
Could you check the issue?

<img width="573" alt="image" src="https://github.com/user-attachments/assets/537b7584-b204-456f-bf10-13b990f7f1ee">

**Comment by jeehoonkang** [comment]
@hongkim9815 Sorry for the inconvenience. I believe now it's resolved.

**Comment by hongkim9815** [comment]
Thanks! It works well :)
