### ISSUE TITLE
[Assignment 4-6] About unit / integration test

### ISSUE THREAD

**Issue by Unknown-Box** [kaist-cp/cs492-uarch#92]
There is two question about unit and integration tests for assignment 4, 5, and 6

1. If the integration test does not generate any failure logs, does it pass?
    1. testbench `matmul` runs totally 8 times in my environment, specifically varies on two cases each of trans_a, trans_b, dataflow. But suddenly I watched a case where the `matmul` bench runs other scenarios like `shift`. Is it okay if it passes only the above 8 cases?
    2. `conv` and `raw_hazard` print less information, even `raw_hazard` doesn't if it seems to be passed. Is there any indicator to know if it passed?
2. My `hw_5.zip` submission still in progress. The test seems that the test has already been ended, but the `VALID` column is `Checking...`. Should I re-submit or not?

**Comment by minseongg** [comment]
### Answer to Question 1:

Yes, if it does not generate explicit failure logs, then it pass.

We have added example output for each benchmark in the assignment description, please check it.

Sorry for the inconvenience.

### Answer to Question 2:

Hmm, it works well for me.

Could you please check again the `VALID` column and if it is still `Checking...`, then could you please submit again?

**Comment by Unknown-Box** [comment]
Thank you so much, it solved all my problems.
