### ISSUE TITLE
Coder io not responding

### ISSUE THREAD

**Issue by kando42** [kaist-cp/cs492-uarch#99]
![image](https://github.com/user-attachments/assets/3ada7145-9223-4d03-90f6-0c93cba38d06)

Dear TA,

I wanted to check my workspace. However the coder page is not responding.

Is it possible to know how to fix the problem?

Thank you very much!

**Comment by minseongg** [comment]
It seems that initializing the Coder page is taking some time. (In my case, it takes about 30 seconds ~ a minute.)

Could you please check if the issue resolves after waiting for a while?

We will check the reason of the issue, sorry for the inconvenience.

**Comment by kando42** [comment]
Thank you very much! 

I tried it few hours ago and currently the page gives error after a while.

![image](https://github.com/user-attachments/assets/c5239a8e-f9c7-4f99-8967-0cbe04efd06e)

**Comment by minseongg** [comment]
Could you please delete the current workspace, create a new one, and try again?

**Comment by kando42** [comment]
Currently, the buttons are inaccessible on my workspace page.

I tried to create a new workspace but I got the following error

![image](https://github.com/user-attachments/assets/4b34487e-8a8a-4e7f-aa99-1792efb58f1f)

**Comment by kando42** [comment]
The page is working well right now thank you very much!

**Comment by hongkim9815** [comment]
I also had a problem with this now .. ㅠㅠ

**Comment by jeehoonkang** [comment]
Recreate a new workspace?
